/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PostsIndexImport } from './routes/posts/index'
import { Route as PostsUsePostsImport } from './routes/posts/usePosts'
import { Route as PostsUsePostImport } from './routes/posts/usePost'
import { Route as PostsPostDetailsImport } from './routes/posts/postDetails'
import { Route as PostsCreatePostFormImport } from './routes/posts/createPostForm'
import { Route as PostsCreatePostActionImport } from './routes/posts/createPostAction'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any)

const PostsUsePostsRoute = PostsUsePostsImport.update({
  id: '/posts/usePosts',
  path: '/posts/usePosts',
  getParentRoute: () => rootRoute,
} as any)

const PostsUsePostRoute = PostsUsePostImport.update({
  id: '/posts/usePost',
  path: '/posts/usePost',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostDetailsRoute = PostsPostDetailsImport.update({
  id: '/posts/postDetails',
  path: '/posts/postDetails',
  getParentRoute: () => rootRoute,
} as any)

const PostsCreatePostFormRoute = PostsCreatePostFormImport.update({
  id: '/posts/createPostForm',
  path: '/posts/createPostForm',
  getParentRoute: () => rootRoute,
} as any)

const PostsCreatePostActionRoute = PostsCreatePostActionImport.update({
  id: '/posts/createPostAction',
  path: '/posts/createPostAction',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/posts/createPostAction': {
      id: '/posts/createPostAction'
      path: '/posts/createPostAction'
      fullPath: '/posts/createPostAction'
      preLoaderRoute: typeof PostsCreatePostActionImport
      parentRoute: typeof rootRoute
    }
    '/posts/createPostForm': {
      id: '/posts/createPostForm'
      path: '/posts/createPostForm'
      fullPath: '/posts/createPostForm'
      preLoaderRoute: typeof PostsCreatePostFormImport
      parentRoute: typeof rootRoute
    }
    '/posts/postDetails': {
      id: '/posts/postDetails'
      path: '/posts/postDetails'
      fullPath: '/posts/postDetails'
      preLoaderRoute: typeof PostsPostDetailsImport
      parentRoute: typeof rootRoute
    }
    '/posts/usePost': {
      id: '/posts/usePost'
      path: '/posts/usePost'
      fullPath: '/posts/usePost'
      preLoaderRoute: typeof PostsUsePostImport
      parentRoute: typeof rootRoute
    }
    '/posts/usePosts': {
      id: '/posts/usePosts'
      path: '/posts/usePosts'
      fullPath: '/posts/usePosts'
      preLoaderRoute: typeof PostsUsePostsImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts/createPostAction': typeof PostsCreatePostActionRoute
  '/posts/createPostForm': typeof PostsCreatePostFormRoute
  '/posts/postDetails': typeof PostsPostDetailsRoute
  '/posts/usePost': typeof PostsUsePostRoute
  '/posts/usePosts': typeof PostsUsePostsRoute
  '/posts': typeof PostsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts/createPostAction': typeof PostsCreatePostActionRoute
  '/posts/createPostForm': typeof PostsCreatePostFormRoute
  '/posts/postDetails': typeof PostsPostDetailsRoute
  '/posts/usePost': typeof PostsUsePostRoute
  '/posts/usePosts': typeof PostsUsePostsRoute
  '/posts': typeof PostsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts/createPostAction': typeof PostsCreatePostActionRoute
  '/posts/createPostForm': typeof PostsCreatePostFormRoute
  '/posts/postDetails': typeof PostsPostDetailsRoute
  '/posts/usePost': typeof PostsUsePostRoute
  '/posts/usePosts': typeof PostsUsePostsRoute
  '/posts/': typeof PostsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/posts/createPostAction'
    | '/posts/createPostForm'
    | '/posts/postDetails'
    | '/posts/usePost'
    | '/posts/usePosts'
    | '/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/posts/createPostAction'
    | '/posts/createPostForm'
    | '/posts/postDetails'
    | '/posts/usePost'
    | '/posts/usePosts'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/posts/createPostAction'
    | '/posts/createPostForm'
    | '/posts/postDetails'
    | '/posts/usePost'
    | '/posts/usePosts'
    | '/posts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PostsCreatePostActionRoute: typeof PostsCreatePostActionRoute
  PostsCreatePostFormRoute: typeof PostsCreatePostFormRoute
  PostsPostDetailsRoute: typeof PostsPostDetailsRoute
  PostsUsePostRoute: typeof PostsUsePostRoute
  PostsUsePostsRoute: typeof PostsUsePostsRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PostsCreatePostActionRoute: PostsCreatePostActionRoute,
  PostsCreatePostFormRoute: PostsCreatePostFormRoute,
  PostsPostDetailsRoute: PostsPostDetailsRoute,
  PostsUsePostRoute: PostsUsePostRoute,
  PostsUsePostsRoute: PostsUsePostsRoute,
  PostsIndexRoute: PostsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/posts/createPostAction",
        "/posts/createPostForm",
        "/posts/postDetails",
        "/posts/usePost",
        "/posts/usePosts",
        "/posts/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/posts/createPostAction": {
      "filePath": "posts/createPostAction.ts"
    },
    "/posts/createPostForm": {
      "filePath": "posts/createPostForm.tsx"
    },
    "/posts/postDetails": {
      "filePath": "posts/postDetails.tsx"
    },
    "/posts/usePost": {
      "filePath": "posts/usePost.ts"
    },
    "/posts/usePosts": {
      "filePath": "posts/usePosts.ts"
    },
    "/posts/": {
      "filePath": "posts/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
